
package co.parameta.pruebatecnica.ws.client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmpleadoPort", targetNamespace = "http://localhost:8081/ws/empleado")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmpleadoPort {


    /**
     * 
     * @param guardarEmpleadoRequest
     * @return
     *     returns co.parameta.pruebatecnica.ws.client.GuardarEmpleadoResponse
     */
    @WebMethod(operationName = "GuardarEmpleado")
    @WebResult(name = "GuardarEmpleadoResponse", targetNamespace = "http://www.parameta.co/empleado", partName = "GuardarEmpleadoResponse")
    public GuardarEmpleadoResponse guardarEmpleado(
        @WebParam(name = "GuardarEmpleadoRequest", targetNamespace = "http://www.parameta.co/empleado", partName = "GuardarEmpleadoRequest")
        GuardarEmpleadoRequest guardarEmpleadoRequest);

}
